/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Principal;

import Clases.OrdenCompra;
import Clases.PorcentajeProveedorRebate;
import Clases.Producto;
import Clases.ProductoOC;
import static DAO.ordenCompraDAO.selectOrdenCompra;
import static DAO.porcentajeProveedorRebateDAO.selectPorcentajeXProveedorRebateLike;
import static DAO.productoDAO.insertProducto;
import static DAO.productoOCDAO.productoOCPorCodigoOC;
import Logica.Logica;
import static Logica.Logica.arrProducto;
import static Logica.Logica.buscaGDT;
import static Logica.Logica.consultaRebate;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.commons.math3.stat.descriptive.summary.Product;

/**
 *
 * @author sopor
 */
public class VentanaPareo extends javax.swing.JDialog {

    /**
     * Creates new form VentanaPareo
     */
    public VentanaPareo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int componentCount = jPanel2.getComponentCount();
        System.out.println("componentCount " + componentCount);

        String todos = "";
        for (int i = 0; i < componentCount; i++) {
            JPanel jpanel = (JPanel) jPanel2.getComponent(i);
            JComboBox jcombobox = (JComboBox) jpanel.getComponent(3);
            String nombre = jcombobox.getSelectedItem().toString();
            System.out.println("nombre " + nombre);
            todos = todos + ", " + nombre;
        }

        todos = todos.replaceFirst(",", "");
        todos = todos.trim();
        System.out.println("todos " + todos);
        List<String> output = new ArrayList<>();
        List<Integer> count = new ArrayList<>();
        findWords(todos, output, count);
        System.out.println(output);
        System.out.println(count);

        System.out.println("BIEN");
        String[] split = todos.split(",");

        for (int i = 0; i < split.length; i++) {
            String codigox = split[i].replace(",", "").trim();
            Producto producto = arrProducto.get(i);
            String codigo = producto.getCodigo();
            String descripcion = producto.getDescripcion();
            String unidad = producto.getUnidad();
            String precioUnitario = producto.getPrecioUnitario();
            String cantidad = producto.getCantidad();
            String precioTotal = producto.getPrecioTotal();
            String folio = producto.getFolio();

            System.out.println("codigo " + codigo);
            System.out.println("descripcion " + descripcion);
            System.out.println("unidad " + unidad);
            System.out.println("precioUnitario " + precioUnitario);
            System.out.println("cantidad " + cantidad);
            System.out.println("precioTotal " + precioTotal);
            System.out.println("folio " + folio);
            System.out.println("codigox " + codigox);

            System.out.println("Aquiiiiiii");
            ProductoOC productoOC = null;
            try {
                productoOC = productoOCPorCodigoOC(codigox, buscaGDT);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPareo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(VentanaPareo.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("productoOC != null " + productoOC != null);
            if (productoOC != null) {
                try {
                    System.out.println("setCostoFinal " + productoOC.getCostoUnitario());
                    producto.setCostoFinal(productoOC.getCostoUnitario());

                    String textContent = productoOC.getCostoUnitario();
                    Double costoUnitario = Double.valueOf(textContent);

                    System.out.println("setCostoUnitario PRE " + costoUnitario);
                    costoUnitario = consultaRebate(buscaGDT, costoUnitario);
                    System.out.println("setCostoUnitario POST " + costoUnitario);

                    String valorFlete = productoOC.getValorFlete();
                    System.out.println("valorFlete " + valorFlete);
                    if (valorFlete != null && !valorFlete.equals("null")) {
                        System.out.println("NO ES NULL");
                        double name = costoUnitario + Double.valueOf(valorFlete);
                        System.out.println("COSTO UNITARIO " + name);
                        double namex = name * 1.025;
                        producto.setCostoUnitario(String.valueOf(namex).replace(",", ""));
                    } else {
                        System.out.println("ES NULL");
                        System.out.println("COSTO UNITARIO " + costoUnitario);
                        double name = costoUnitario * 1.025;
                        producto.setCostoUnitario(String.valueOf(name).replace(",", ""));
                    }

                    producto.setNumeroOC(productoOC.getNumeroOC());
                    producto.setCodigoOC(productoOC.getCodigo());
                    producto.setCantidadOC(productoOC.getCantidad());

                    try {
                        insertProducto(producto);
                    } catch (IOException ex) {
                        Logger.getLogger(VentanaPareo.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(VentanaPareo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(VentanaPareo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaPareo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            System.out.println("/////////////////////////////////////////");
        }
        JOptionPane.showMessageDialog(Principal.newJFrame, "Factura ingresada correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private static void findWords(String s, List<String> output, List<Integer> count) {
        String[] words = s.split(", ");
        Map<String, Integer> map = new LinkedHashMap<>();
        Arrays.stream(words).forEach(e -> map.put(e, map.getOrDefault(e, 0) + 1));
        map.forEach((k, v) -> {
            output.add(k);
            count.add(v);
        });
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
