package Principal;

import Clases.Vendedor;
import DAO.consultaClienteVEDAO;
import DAO.consultaVendedorVEDAO;
import static DAO.consultaVendedorVEDAO.consultaVendedoresVE;
import static Logica.LogicaVE.cargaTabla;
import static Logica.LogicaVE.ventanaVE;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

public class VentanaVE extends javax.swing.JFrame {

    public VentanaVE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        Menu.setText("Menu");

        jMenuItem1.setText("Agregar Vendedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem1);

        jMenuItem2.setText("Quitar Vendedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem2);

        jMenuItem4.setText("Cliente Sin Asignacion");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem4);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        VentanaPrincipal.jButton11.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            JTextField jpf = new JTextField(20);

            UpperCaseDocument ucd = new UpperCaseDocument();
            jpf.setDocument(ucd);

            JLabel jl = new JLabel("Nombre Vendedor: ");
            Box box = Box.createHorizontalBox();
            box.add(jl);
            box.add(jpf);
            int x = JOptionPane.showConfirmDialog(Principal.newJFrame, box, "Agregar Vendedor", JOptionPane.OK_CANCEL_OPTION);
            String input = "";

            if (x == JOptionPane.OK_OPTION) {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(Principal.newJFrame, "Crear Vendedor?", "Crear?", dialogButton);

                if (dialogResult == 0) {
                    input = jpf.getText();
                    boolean registraVendedor = consultaVendedorVEDAO.registraVendedor(input);
                    if (registraVendedor) {
                        JOptionPane.showMessageDialog(null, "Vendedor Creado", "Creado", JOptionPane.INFORMATION_MESSAGE);

                        JPanel cargaTabla = cargaTabla();

                        ventanaVE.jScrollPane1.setViewportView(cargaTabla);
                        ventanaVE.revalidate();
                        ventanaVE.repaint();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Crear Vendedor", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaVE.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaVE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            JComboBox jpf = new JComboBox();
            ArrayList<Vendedor> consultaVendedoresVE = consultaVendedoresVE();
            for (int i = 0; i < consultaVendedoresVE.size(); i++) {
                jpf.addItem(consultaVendedoresVE.get(i).getNombre());
            }

            JLabel jl = new JLabel("Eliminar a (Esto eliminara ademas a todo sus clientes): ");
            Box box = Box.createHorizontalBox();
            box.add(jl);
            box.add(jpf);
            int x = JOptionPane.showConfirmDialog(Principal.newJFrame, box, "Eliminar Vendedor", JOptionPane.OK_CANCEL_OPTION);
            String input = "";

            if (x == JOptionPane.OK_OPTION) {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(Principal.newJFrame, "Quieres Eliminar?", "Eliminar?", dialogButton);

                if (dialogResult == 0) {
                    input = jpf.getSelectedItem().toString();
                    boolean eliminaClientesVE = consultaClienteVEDAO.eliminaClientesVE(input);
                    if (eliminaClientesVE) {

                        boolean eliminaVendedorVE = consultaVendedorVEDAO.eliminaVendedorVE(input);

                        if (eliminaVendedorVE) {

                            JOptionPane.showMessageDialog(null, "Vendedor Eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);

                            JPanel cargaTabla = cargaTabla();

                            ventanaVE.jScrollPane1.setViewportView(cargaTabla);
                            ventanaVE.revalidate();
                            ventanaVE.repaint();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Eliminar Vendedor", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Clientes del Vendedor", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaVE.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaVE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        VentanaClientesSinAsignacion ventanaClientesSinAsignacion = new VentanaClientesSinAsignacion();
        ventanaClientesSinAsignacion.setLocationRelativeTo(this);
        ventanaClientesSinAsignacion.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Prueba().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

class UpperCaseDocument extends PlainDocument {

    private boolean upperCase = true;

    public void setUpperCase(boolean flag) {
        upperCase = flag;
    }

    public void insertString(int offset, String str, AttributeSet attSet)
            throws BadLocationException {
        if (upperCase) {
            str = str.toUpperCase();
        }
        super.insertString(offset, str, attSet);
    }
}
